### ISSUE TITLE
Bug: 1.3 version stops working

### ISSUE THREAD

**Issue by SylwesterZarebski** [KhaosCoders/VSCodeBlockEndTag#10]
With version 1.3 there are no tags. Settings works - extension is loaded correctly.

**Comment by Khaos66** [comment]
So no crash, just no tags?
I'll need to know your setup: which Visual Studio and what other extensions?

**Comment by SylwesterZarebski** [comment]
Visual Studio 2015 and multiple other extensions, but the same list of them before upgrading. Could You make a release on GitHub with previous version (1.2) to confirm it?

VS info:

> Microsoft Visual Studio Professional 2015
> Version 14.0.25431.01 Update 3
> Microsoft .NET Framework
> Version 4.6.01586
> 
> Installed Version: Professional
> 
> LightSwitch for Visual Studio 2015   00322-50050-03552-AA310
> Microsoft LightSwitch for Visual Studio 2015
> 
> Microsoft Visual Studio Tools for Applications 2015   00322-50050-03552-AA310
> Microsoft Visual Studio Tools for Applications 2015
> 
> Visual Basic 2015   00322-50050-03552-AA310
> Microsoft Visual Basic 2015
> 
> Visual C# 2015   00322-50050-03552-AA310
> Microsoft Visual C# 2015
> 
> Visual C++ 2015   00322-50050-03552-AA310
> Microsoft Visual C++ 2015
> 
> Windows Phone SDK 8.0 - ENU   00322-50050-03552-AA310
> Windows Phone SDK 8.0 - ENU
> 
> ASP.NET and Web Tools 2015.1   14.1.21111.0
> ASP.NET and Web Tools 2015.1
> 
> ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
> For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563
> 
> ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
> For additional information, visit http://www.asp.net/
> 
> Azure App Service Tools v2.9.6   14.0.21111.0
> Azure App Service Tools v2.9.6
> 
> Azure Data Lake Node   1.0
> This package contains the Data Lake integration nodes for Server Explorer.
> 
> Azure Data Lake Tools for Visual Studio   2.2.2100.0
> Microsoft Azure Data Lake Tools for Visual Studio
> 
> BetterStartPage   1.0
> This is a VS2015 like start page which replaces the news section by a custom project dashboard.
> In the project dashboard you can organize your solutions and projects into different groups for fast access. 
> 
> To edit the dashboard right-click on the empty area and enable the edit mode in the context menu. 
> Add new groups by clicking on the "Add Group" link on the bottom, add new projects to the group by dragging Solution or Project files from the explorer to the groups. 
> You can reorder or delete groups and projects by using the action buttons beside the items.
> 
> Clear MEF Component Cache   1.3.1
> Clears the Visual Studio MEF component cache to fix issues with cache corruption.
> 
> CodeMaid   10.2.7
> CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.
> 
> Command Bus, Event Stream and Async Manager   Merq
> Provides ICommandBus, IEventStream and IAsyncManager MEF services for loosely coupled Visual Studio extension components communication and integration.
> 
> Common Azure Tools   1.8
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> CSProjHell   1.0
> Solution for .csproj file hell when working with vcs outside of visual studio. Since csproj files are not automatically saved, often they are commited with new files missing, therefore forcing you to discard your changes and re-add them. Happens mainly if your project is javascript heavy.
> 
> DisableNoSourceAvailableTab 3   1.0
> Information about my package
> 
> Extensibility Tools   1.10.188
> Contains numerous tools and helpers that makes it easier than ever to build Visual Studio extensions.
> 
> File Nesting   2.6.67
> Automatically nest files based on file name and enables developers to nest and unnest any file manually
> 
> I Hate #Regions   1.0
> Regions Suck.  You need this.
> 
> Indent Guides   15
> Indent Guides
> 
> Adds visual guides at each indentation level.
> 
> Insert Identifier   1.0
> Insert GUIDs and IDs into the active editor using a menu option or keyboard shortcut. Most useful when creating setups with WiX, when many unique IDs are required.
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> JavaScript Project System   2.0
> JavaScript Project System
> 
> KC CodeBlock End Tag Extension   1.0
> Adds an end tag to each code block with information about the header / condition
> 
> LocalHistory   1.0
> Information about my package
> 
> Microsoft .NET Core Tools (Preview 2)   14.1.21111.0
> Microsoft .NET Core Tools (Preview 2)
> 
> Microsoft Azure Hive Query Language Service   2.2.2100.0
> Language service for Hive query
> 
> Microsoft Azure Mobile Services Tools   1.4
> Microsoft Azure Mobile Services Tools
> 
> Microsoft Azure Tools   2.9
> Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.41104.6
> 
> NuGet Package Manager   3.5.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> Office Developer Tools for Visual Studio 2015 ENU   14.0.23928
> Microsoft Office Developer Tools for Visual Studio 2015 ENU
> 
> PreEmptive Analytics Visualizer   1.2
> Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.
> 
> Soneta.StudioExt.Package   1.0
> Visual Studio single file generator for BusienessGenerator.exe
> 
> SQL Server Data Tools   14.0.61021.0
> Microsoft SQL Server Data Tools
> 
> SQL Server Integration Services   
> Microsoft SQL Server Integration Services Designer
> Version 13.0.1601.5
> 
> ToolWindowHostedEditor   1.0
> Hosting json editor into a tool window
> 
> Trailing Whitespace Visualizer   2.5.83
> Keeps your code files clean by making it easier than ever to identify and remove any trailing whitespace
> 
> TypeScript   1.8.36.0
> TypeScript tools for Visual Studio
> 
> Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
> An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
> https://GitHub.com/EWSoftware/VSSpellChecker
> 
> Visual Studio Spell Checker   VSSpellChecker
> An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
> https://GitHub.com/EWSoftware/VSSpellChecker
> 
> Visual Studio Tools for Universal Windows Apps   14.0.25527.01
> The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.
> 
> VisualHG   1.1.7
> Mercurial source contol provider.
> 
> VSColorOutput   2.5
> Color output for build and debug windows - http://mike-ward.net/vscoloroutput
> 
> Windows Installer XML Toolset   3.10.3.3007
> Windows Installer XML Toolset version 3.10.3.3007
> Copyright (c) .NET Foundation and contributors. All rights reserved.
> 
> Workflow Manager Tools 1.0   1.0
> This package contains the necessary Visual Studio integration components for Workflow Manager.
> 
> Xamarin   4.2.1.62 (680125b)
> Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
> 
> Xamarin.Android   7.0.2.37 (ce955cc)
> Visual Studio extension to enable development for Xamarin.Android.
> 
> Xamarin.iOS   10.2.1.5 (44931ae)
> Visual Studio extension to enable development for Xamarin.iOS.
> 
> XamlStylerVSPackage   1.0
> XAML Styler.

**Comment by Khaos66** [comment]
Please try the following two things:
1. reinstall the extension
2. try the "show tags always" option

**Comment by SylwesterZarebski** [comment]
I've do this already. Uninstalled+restart, installed+restart, then disabled in options+restart, enabled+restart etc. I'm using Show tags "Always", but also changed to "When header not visible" and back...
Also checked on another machine with only few extensions and also no end tags :(

**Comment by Khaos66** [comment]
Fixed it in version 1.4 ;) Enjoy!

**Comment by SylwesterZarebski** [comment]
Thanks a lot, it works now. You're great :).
