### ISSUE TITLE
FontSize too small in version 1.3

### ISSUE THREAD

**Issue by DimitarCC** [KhaosCoders/VSCodeBlockEndTag#11]
The fontsize and icons are soooo small in version 1.3 and VS 2017

![image](https://cloud.githubusercontent.com/assets/1904901/24346715/442236ac-12de-11e7-9b59-b79107e418ce.png)

**Comment by Khaos66** [comment]
Yes, you're right. It will be fixed in version 1.4 ;)

**Comment by DimitarCC** [comment]
It is quite better in version 1.4. The text is readable now. What i think will be good in addition is 2 things:
1. The text should be centered vertically with icon. Now it appears a bit on the bottom
2. It will be good if there is somekind of hover effect over the text so to know you can do something with it. Maybe fade in/out or hand cursor?
