### ISSUE TITLE
EndTag text overlaps over the code (ver 1.4)

### ISSUE THREAD

**Issue by DimitarCC** [KhaosCoders/VSCodeBlockEndTag#12]
With changes in version 1.4 endtag text and icon start to overlaps the code and make it unreadble.
Maybe that is due to the fact it is used canvas instead of stackpanel and there is no more space reserved for the tag items.

![image](https://cloud.githubusercontent.com/assets/1904901/24394652/73f4deb2-13a5-11e7-99db-472412b179aa.png)

**Comment by Khaos66** [comment]
Yes, very annoying, I know... Sorry for that one!
Will be fixed with next release ;)
