### ISSUE TITLE
End Tagger prevents the end of line from being clicked

### ISSUE THREAD

**Issue by wmjordan** [KhaosCoders/VSCodeBlockEndTag#13]
I am using the "Navigate on: Double Click" configuration.
Without end tagger, when I single click on the end of the line, the caret moves to after the last character at that line; when end tagger is turned on, nothing happened.
Could you please place the caret at the end of the line when "Navigate on: Double Click" is chosen and we click on the end tagger.

#7 has a similar requirement. Please implement the alike behavior for the double click configuration.

**Comment by Khaos66** [comment]
I've had this enabled at first, but it broke the double-click completely. Since the tag disappeared after one click there was no canche to double-click it.

It'll need some timeout implemented to wait and count the clicks. I'll see what I can do.

**Comment by Khaos66** [comment]
I've figured it out and you can find it in version 1.5
