### ISSUE TITLE
Error: "CBETagPackage" package did not load correctly

### ISSUE THREAD

**Issue by CePur** [KhaosCoders/VSCodeBlockEndTag#24]
![resim](https://user-images.githubusercontent.com/36715887/137321286-085d362d-fa50-423e-a93d-68e595612171.png)

![resim](https://user-images.githubusercontent.com/36715887/137321740-bda055fc-73d0-4363-bf81-22c5f07b859b.png)

**Comment by gagmeng** [comment]
<record>3237</record>
    <time>2021/10/18 03:01:35.435</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [CBETagPackage]Source: &apos;mscorlib&apos; Description: &#x672A;&#x80FD;&#x52A0;&#x8F7D;&#x6587;&#x4EF6;&#x6216;&#x7A0B;&#x5E8F;&#x96C6;&#x201C;Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&#x201D;&#x6216;&#x5B83;&#x7684;&#x67D0;&#x4E00;&#x4E2A;&#x4F9D;&#x8D56;&#x9879;&#x3002;&#x7CFB;&#x7EDF;&#x627E;&#x4E0D;&#x5230;&#x6307;&#x5B9A;&#x7684;&#x6587;&#x4EF6;&#x3002;&#x000D;&#x000A;System.IO.FileNotFoundException: &#x672A;&#x80FD;&#x52A0;&#x8F7D;&#x6587;&#x4EF6;&#x6216;&#x7A0B;&#x5E8F;&#x96C6;&#x201C;Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&#x201D;&#x6216;&#x5B83;&#x7684;&#x67D0;&#x4E00;&#x4E2A;&#x4F9D;&#x8D56;&#x9879;&#x3002;&#x7CFB;&#x7EDF;&#x627E;&#x4E0D;&#x5230;&#x6307;&#x5B9A;&#x7684;&#x6587;&#x4EF6;&#x3002;&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;&#x8B66;&#x544A;: &#x7A0B;&#x5E8F;&#x96C6;&#x7ED1;&#x5B9A;&#x65E5;&#x5FD7;&#x8BB0;&#x5F55;&#x88AB;&#x5173;&#x95ED;&#x3002;&#x000D;&#x000A;&#x8981;&#x542F;&#x7528;&#x7A0B;&#x5E8F;&#x96C6;&#x7ED1;&#x5B9A;&#x5931;&#x8D25;&#x65E5;&#x5FD7;&#x8BB0;&#x5F55;&#xFF0C;&#x8BF7;&#x5C06;&#x6CE8;&#x518C;&#x8868;&#x503C; [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)&#x8BBE;&#x7F6E;&#x4E3A; 1&#x3002;&#x000D;&#x000A;&#x6CE8;&#x610F;: &#x4F1A;&#x6709;&#x4E00;&#x4E9B;&#x4E0E;&#x7A0B;&#x5E8F;&#x96C6;&#x7ED1;&#x5B9A;&#x5931;&#x8D25;&#x65E5;&#x5FD7;&#x8BB0;&#x5F55;&#x5173;&#x8054;&#x7684;&#x6027;&#x80FD;&#x635F;&#x5931;&#x3002;&#x000D;&#x000A;&#x8981;&#x5173;&#x95ED;&#x6B64;&#x529F;&#x80FD;&#xFF0C;&#x8BF7;&#x79FB;&#x9664;&#x6CE8;&#x518C;&#x8868;&#x503C; [HKLM\Software\Microsoft\Fusion!EnableLog]&#x3002;&#x000D;&#x000A;</description>
    <guid>{D7C91E0F-240B-4605-9F35-ACCF63A68623}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>

**Comment by Khaos66** [comment]
Thanks for reporting. I'll fix it with the next release ;)
I guess I shouldn't have updated the nuget dependencies...

**Comment by gagmeng** [comment]
> It should be fixed now. Let me know if it isn't. And please close this issue if it is =)
Thanks
