### ISSUE TITLE
Feature request: Strip unnecessary space chars from tag

### ISSUE THREAD

**Issue by SylwesterZarebski** [KhaosCoders/VSCodeBlockEndTag#4]
Hi,
  When i have multiline `if` then tag concatenate these multiple lines (it is ok), but it does this with concatenating all characters. It should strip space characters from tag.
Example:
```
if (a & b
           & c)
{
} if (a & b           & c)
```
Tag line should be:
```
} if (a & b & c)
```

**Comment by Khaos66** [comment]
Did it!
Hope you'll like version 1.2 ;)
