### ISSUE TITLE
Feature request: Allow to click on code block end tag when CTRL+click is set in options

### ISSUE THREAD

**Issue by SylwesterZarebski** [KhaosCoders/VSCodeBlockEndTag#7]
It is useful to allow clicking on code block end tag to set cursor to end of chosen line when i've set CTRL+click in options. Now clicking end tag does nothing.

**Comment by Khaos66** [comment]
Sorry, I don't get it...
When CTRL+Click in enabled, a single click (without CTRL pressed) does nothing? That's right.
When you press CTRL (left or right) and click then, does it jump to the beginning of the codition?

**Comment by SylwesterZarebski** [comment]
Yes, it does nothing, but it could allow to enter this line like clicking after tag.

**Comment by Khaos66** [comment]
Ahhh, now I see... So, CTRL+Click does work. But you want to jump to the end of the condition with the 'simple' click? 
That should be possible ;)

**Comment by SylwesterZarebski** [comment]
I feel i do not give enough information :).

Now when i set CTRL+click to move cursor to beginning, simple click on tag do not do anything - this is proper current behaviour.
But then goes this feature request - to allow single clicking on this tag, but then it should not be moving cursor anywhere but behave as there was not tag at all and setting cursor after }.
Of course it should work like that only if CTRL+click (or anything different than single click) is selected in options.

**Comment by Khaos66** [comment]
Thank you, now I get it ;)

**Comment by Khaos66** [comment]
Did it in version 1.3
