### ISSUE TITLE
Bug: Exception when pasting code

### ISSUE THREAD

**Issue by SylwesterZarebski** [KhaosCoders/VSCodeBlockEndTag#9]
Sometimes on pasting code, i'm getting addon exception in VS editor. In ActivityLog.xml are multiple lines with the same exception from Your addon. Below i'm pasting one of these lines:

> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: span at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetText(Span span) at Microsoft.VisualStudio.Text.Implementation.TextSnapshot.GetText(Span span) at Microsoft.VisualStudio.Text.Implementation.BaseSnapshot.GetText(Int32 startIndex, Int32 length) at CodeBlockEndTag.CBETagger.IsTagVisible(Int32 start, Int32 end, Nullable\`1 visibleSpan, ITextSnapshot snapshot) at CodeBlockEndTag.CBETagger.GetTagsCore(SnapshotSpan span) at CodeBlockEndTag.CBETagger.GetTags(SnapshotSpan span) at CodeBlockEndTag.CBETagger.<Microsoft-VisualStudio-Text-Tagging-ITagger<Microsoft-VisualStudio-Text-Editor-IntraTextAdornmentTag>-GetTags>d__16.MoveNext() at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__38.MoveNext()

**Comment by Khaos66** [comment]
Thank you for this report!
I've done some changes to prevent this.
Find it fixed in version 1.3

**Comment by SylwesterZarebski** [comment]
Thanks a lot, i'll check it asap :).

**Comment by Khaos66** [comment]
I'll release it tomorrow ;)
